{"uuid": "0db154a2-e53c-4c06-985f-1687bfbe8b17", "children": ["d101bbad-40d4-4543-90d2-ca18fa613778"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "Failed: Не удалось загрузить страницу: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=136.0.7103.93)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6E648CF25+75717]\n\tGetHandleVerifier [0x00007FF6E648CF80+75808]\n\t(No symbol) [0x00007FF6E6258F9A]\n\t(No symbol) [0x00007FF6E6231B41]\n\t(No symbol) [0x00007FF6E62DEC2E]\n\t(No symbol) [0x00007FF6E62FECC2]\n\t(No symbol) [0x00007FF6E62D7153]\n\t(No symbol) [0x00007FF6E62A0421]\n\t(No symbol) [0x00007FF6E62A11B3]\n\tGetHandleVerifier [0x00007FF6E678D6FD+3223453]\n\tGetHandleVerifier [0x00007FF6E6787CA2+3200322]\n\tGetHandleVerifier [0x00007FF6E67A5AD3+3322739]\n\tGetHandleVerifier [0x00007FF6E64A69FA+180890]\n\tGetHandleVerifier [0x00007FF6E64AE0FF+211359]\n\tGetHandleVerifier [0x00007FF6E6495274+109332]\n\tGetHandleVerifier [0x00007FF6E6495422+109762]\n\tGetHandleVerifier [0x00007FF6E647BA39+4825]\n\tBaseThreadInitThunk [0x00007FFA0CCF7374+20]\n\tRtlUserThreadStart [0x00007FFA0D13CC91+33]\n\n", "trace": "  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Юлия\\OneDrive\\Desktop\\jULL\\Skypro\\aviasales_autotests\\tests\\test_ui.py\", line 26, in setup\n    pytest.fail(f\"Не удалось загрузить страницу: {str(e)}\")\n  File \"C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\outcomes.py\", line 188, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1747161285047, "stop": 1747161286264}], "start": 1747161285047, "stop": 1747161286330}