{"name": "test_search_form", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=49967): Read timed out. (read timeout=120)", "trace": "C:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py:534: in _make_request\n    response = conn.getresponse()\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connection.py:516: in getresponse\n    httplib_response = super().getresponse()\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:1428: in getresponse\n    response.begin()\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:331: in begin\n    version, status, reason = self._read_status()\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py:708: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\ntests\\test_ui.py:15: in setup\n    browser.get(Settings.BASE_URL)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:473: in get\n    self.execute(Command.GET, {\"url\": url})\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:446: in execute\n    response = self.command_executor.execute(driver_command, params)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:404: in execute\n    return self._request(command_info[0], url, body=data)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:428: in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py:143: in request\n    return self.request_encode_body(\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\_request_methods.py:278: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\poolmanager.py:443: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py:841: in urlopen\n    retries = retries.increment(\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\retry.py:474: in increment\n    raise reraise(type(error), error, _stacktrace)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\util\\util.py:39: in reraise\n    raise value\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py:787: in urlopen\n    response = self._make_request(\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py:536: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\nC:\\Users\\Юлия\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\urllib3\\connectionpool.py:367: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=49967): Read timed out. (read timeout=120)"}, "start": 1747160436942, "stop": 1747160436942, "uuid": "0541b73e-fd0c-4eb2-b079-e8d28c6c9350", "historyId": "e5c63d0849972fdfc81222bba6fb903e", "testCaseId": "e5c63d0849972fdfc81222bba6fb903e", "fullName": "tests.test_ui.TestAviasalesUI#test_search_form", "labels": [{"name": "story", "value": "2. Проверка формы поиска"}, {"name": "feature", "value": "UI Тесты Aviasales"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "TestAviasalesUI"}, {"name": "host", "value": "DESKTOP-40TG5MB"}, {"name": "thread", "value": "14088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui"}]}